import { describe, test, expect } from "bun:test";
import { join } from "node:path";
import { generateBundle } from "../src/bundler.js";
import { buildDependencyGraph } from "../src/graph.js";
import { discoverFiles, discoverSharedFiles } from "../src/discovery.js";

const FIXTURES = join(import.meta.dir, "fixtures");

async function buildBundle(fixture: string, runtime: "client" | "server") {
	const runtimeFiles = await discoverFiles(join(FIXTURES, fixture), runtime);
	const sharedFiles = await discoverSharedFiles(join(FIXTURES, fixture));
	const files = [...runtimeFiles, ...sharedFiles];
	const graph = buildDependencyGraph(files, runtime);
	return generateBundle(graph);
}

describe("generateBundle", () => {
	test("includes header comment", async () => {
		const bundle = await buildBundle("basic-resource", "client");
		expect(bundle).toContain("-- FiveM Lua Bundle (client)");
		expect(bundle).toContain("-- Generated by fivem-lua-bundler");
	});

	test("registers modules in package.preload", async () => {
		const bundle = await buildBundle("basic-resource", "client");
		expect(bundle).toContain('package.preload["modules.utils"]');
		expect(bundle).toContain('package.preload["shared.config"]');
	});

	test("uses unprefixed module IDs in package.preload", async () => {
		const bundle = await buildBundle("basic-resource", "client");
		expect(bundle).not.toContain('package.preload["client.');
	});

	test("executes entry points in do...end blocks", async () => {
		const bundle = await buildBundle("basic-resource", "client");
		const doBlocks = bundle.match(/^do$/gm);
		expect(doBlocks).toBeTruthy();
		expect(doBlocks!.length).toBeGreaterThan(0);
	});

	test("does not execute shared files as entry points", async () => {
		const bundle = await buildBundle("basic-resource", "client");
		const entrySection = bundle.split(/^do$/m).slice(1).join("\ndo\n");
		expect(entrySection).not.toContain("debug = false");
	});

	test("produces deterministic output", async () => {
		const bundle1 = await buildBundle("basic-resource", "client");
		const bundle2 = await buildBundle("basic-resource", "client");
		const strip = (b: string) => b.replace(/-- Build:.*/, "-- Build: TIMESTAMP");
		expect(strip(bundle1)).toBe(strip(bundle2));
	});
});
