import { getModulesInDependencyOrder } from "./graph.js";
import type { DependencyGraph, ParsedModule } from "./types.js";

export function generateBundle(graph: DependencyGraph): string {
	const modules = getModulesInDependencyOrder(graph);

	const parts: string[] = [];

	parts.push(generateHeader(graph));
	parts.push(generatePreloadRegistry(modules));
	parts.push(generateEntryExecution(graph.entryPoints));

	return parts.join("\n\n");
}

function generateHeader(graph: DependencyGraph): string {
	return (
		`-- FiveM Lua Bundle (${graph.runtime})\n` +
		`-- Generated by fivem-lua-bundler\n` +
		`-- DO NOT EDIT - This file is auto-generated\n` +
		`--\n` +
		`-- Module count: ${graph.modules.size}\n` +
		`-- Build: ${new Date().toISOString()}`
	);
}

function generatePreloadRegistry(modules: ParsedModule[]): string {
	const lines: string[] = [];

	for (const module of modules) {
		lines.push(
			`package.preload["${escapeString(module.id)}"] = ${module.wrappedCode}`,
		);
	}

	return lines.join("\n");
}

function generateEntryExecution(entryPoints: ParsedModule[]): string {
	if (entryPoints.length === 0) {
		return "-- No entry points to execute";
	}

	const lines: string[] = [];

	for (const entry of entryPoints) {
		lines.push("");
		lines.push(`do`);
		lines.push(indentCode(entry.source.content, 1));
		lines.push(`end`);
	}

	return lines.join("\n");
}

function indentCode(code: string, tabs: number): string {
	const indent = "\t".repeat(tabs);
	return code
		.split("\n")
		.map((line) => (line.trim() ? indent + line : line))
		.join("\n");
}

function escapeString(str: string): string {
	return str
		.replace(/\\/g, "\\\\")
		.replace(/"/g, '\\"')
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t");
}
